---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: slurm-config
data:
  slurm.conf: |
    # slurm.conf
    #
    # See the slurm.conf man page for more information.
    #
    ClusterName=linux
    ControlMachine=slurmctld
    ControlAddr=slurmctld
    #BackupController=
    #BackupAddr=
    #
    SlurmUser=slurm
    #SlurmdUser=root
    SlurmctldPort=6817
    SlurmdPort=6818
    AuthType=auth/munge
    #JobCredentialPrivateKey=
    #JobCredentialPublicCertificate=
    StateSaveLocation=/var/lib/slurmd
    SlurmdSpoolDir=/var/spool/slurmd
    SwitchType=switch/none
    MpiDefault=none
    SlurmctldPidFile=/var/run/slurmd/slurmctld.pid
    SlurmdPidFile=/var/run/slurmd/slurmd.pid
    ProctrackType=proctrack/linuxproc
    #PluginDir=
    #CacheGroups=0
    #FirstJobId=
    ReturnToService=0
    #MaxJobCount=
    #PlugStackConfig=
    #PropagatePrioProcess=
    #PropagateResourceLimits=
    #PropagateResourceLimitsExcept=
    #Prolog=
    #Epilog=
    #SrunProlog=
    #SrunEpilog=
    #TaskProlog=
    #TaskEpilog=
    #TaskPlugin=
    #TrackWCKey=no
    #TreeWidth=50
    #TmpFS=
    #UsePAM=
    #
    # TIMERS
    SlurmctldTimeout=300
    SlurmdTimeout=300
    InactiveLimit=0
    MinJobAge=300
    KillWait=30
    Waittime=0
    #
    # SCHEDULING
    SchedulerType=sched/backfill
    #SchedulerAuth=
    #SchedulerPort=
    #SchedulerRootFilter=
    SelectType=select/cons_res
    SelectTypeParameters=CR_CPU_Memory
    FastSchedule=1
    #PriorityType=priority/multifactor
    #PriorityDecayHalfLife=14-0
    #PriorityUsageResetPeriod=14-0
    #PriorityWeightFairshare=100000
    #PriorityWeightAge=1000
    #PriorityWeightPartition=10000
    #PriorityWeightJobSize=1000
    #PriorityMaxAge=1-0
    #
    # LOGGING
    SlurmctldDebug=3
    SlurmctldLogFile=/var/log/slurm/slurmctld.log
    SlurmdDebug=3
    SlurmdLogFile=/var/log/slurm/slurmd.log
    JobCompType=jobcomp/filetxt
    JobCompLoc=/var/log/slurm/jobcomp.log
    #
    # ACCOUNTING
    JobAcctGatherType=jobacct_gather/linux
    JobAcctGatherFrequency=30
    #
    AccountingStorageType=accounting_storage/slurmdbd
    AccountingStorageHost=slurmdbd
    AccountingStoragePort=6819
    #AccountingStorageLoc=slurm_acct_db
    #AccountingStoragePass=
    #AccountingStorageUser=
    #
    # COMPUTE NODES
    #GresTypes=gpu
    NodeName=nvidia-node01  NodeAddr=10.227.209.181 Gres=gpu:8     CPUs=2 Sockets=1 CoresPerSocket=2 ThreadsPerCore=2 Procs=40 RealMemory=10000 State=UNKNOWN
    NodeName=nvidia-node02  NodeAddr=10.227.209.182 Gres=gpu:8     CPUs=2 Sockets=1 CoresPerSocket=2 ThreadsPerCore=2 Procs=40 RealMemory=10000 State=UNKNOWN
    NodeName=slurmd RealMemory=1000 State=UNKNOWN
    #
    # PARTITIONS
    PartitionName=Test Default=yes Nodes=ALL MaxTime=00:10:00 DefaultTime=00:10:00 State=UP OverSubscribe=NO

    PartitionName=Basic Nodes=ALL MaxTime=00:10:00 DefaultTime=00:10:00 State=UP OverSubscribe=NO
    PartitionName=Short Nodes=ALL MaxTime=01:00:00 DefaultTime=01:00:00 State=UP OverSubscribe=NO
    PartitionName=Medium Nodes=ALL MaxTime=04:00:00 DefaultTime=04:00:00 State=UP OverSubscribe=NO
    PartitionName=Long Nodes=ALL MaxTime=10:00:00 DefaultTime=10:00:00 State=UP OverSubscribe=NO
    PartitionName=Mammoth Nodes=ALL MaxTime=14-00:00:00 DefaultTime=14-00:00:00 State=UP OverSubscribe=NO


  slurmdbd.conf: |
    #
    # Example slurmdbd.conf file.
    #
    # See the slurmdbd.conf man page for more information.
    #
    # Archive info
    #ArchiveJobs=yes
    #ArchiveDir="/tmp"
    #ArchiveSteps=yes
    #ArchiveScript=
    #JobPurge=12
    #StepPurge=1
    #
    # Authentication info
    AuthType=auth/munge
    #AuthInfo=/var/run/munge/munge.socket.2
    #
    # slurmDBD info
    DbdAddr=slurmdbd
    DbdHost=slurmdbd
    #DbdPort=6819
    SlurmUser=slurm
    #MessageTimeout=300
    DebugLevel=4
    #DefaultQOS=normal,standby
    LogFile=/var/log/slurm/slurmdbd.log
    PidFile=/var/run/slurmdbd/slurmdbd.pid
    #PluginDir=/usr/lib/slurm
    #PrivateData=accounts,users,usage,jobs
    #TrackWCKey=yes
    #
    # Database info
    StorageType=accounting_storage/mysql
    StorageHost=mysql
    StorageUser=slurm
    StoragePass=9dd1d5c19c293f0c417d6fb8
    StorageLoc=slurm_acct_db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmdbd
  labels:
    app: slurmdbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmdbd
  template:
    metadata:
      labels:
        app: slurmdbd
    spec:
      hostname: slurmdbd
      containers:
        # slurmdbd
        - name: slurmdbd
          image: docker.io/kalenpeterson/slurm-docker-cluster:v18
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/docker-entrypoint.sh"]
          args:
            - "slurmdbd"
          # command: ["/bin/sh", "-c"]
          # args:
          #   - "sleep infinity"
          ports:
            - name: slurmdbd
              protocol: TCP
              containerPort: 6819
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6819
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 5
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6819
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf.injected
              subPath: slurm.conf
              name: slurm-config
            - mountPath: /etc/slurm/slurmdbd.conf.injected
              subPath: slurmdbd.conf
              name: slurm-config
            - mountPath: /var/log/slurm
              name: var-log-slurm
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config
            defaultMode: 0600
        - name: var-log-slurm
          persistentVolumeClaim:
            claimName: var-log-slurm
        - name: var-lib-slurmd
          persistentVolumeClaim:
            claimName: var-lib-slurmd
        - name: var-spool-slurmd
          persistentVolumeClaim:
            claimName: var-spool-slurmd
        - name: data
          hostPath:
            path: /nas/slurm/data
            type: Directory
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmctld
  labels:
    app: slurmctld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmctld
  template:
    metadata:
      labels:
        app: slurmctld
    spec:
      hostname: slurmctld
      # Host Records for Nodes
      hostAliases:
        - ip: "10.227.209.181"
          hostnames:
            - "nvidia-node01"
      containers:
      #  slurmctld
        - name: slurmctld
          image: docker.io/kalenpeterson/slurm-docker-cluster:v18
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/docker-entrypoint.sh"]
          args:
            - "slurmctld"
          # command: ["/bin/sh", "-c"]
          # args:
          #   - "sleep infinity"
          ports:
            - name: slurmctld
              protocol: TCP
              containerPort: 6817
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6817
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 5
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6817
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf.injected
              subPath: slurm.conf
              name: slurm-config
            - mountPath: /etc/slurm/slurmdbd.conf.injected
              subPath: slurmdbd.conf
              name: slurm-config
            - mountPath: /var/log/slurm
              name: var-log-slurm
            - mountPath: /var/lib/slurmd
              name: var-lib-slurmd
            - mountPath: /var/spool/slurmd
              name: var-spool-slurmd
            - mountPath: /data
              name: data
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config
            defaultMode: 0600
        - name: var-log-slurm
          persistentVolumeClaim:
            claimName: var-log-slurm
        - name: var-lib-slurmd
          persistentVolumeClaim:
            claimName: var-lib-slurmd
        - name: var-spool-slurmd
          persistentVolumeClaim:
            claimName: var-spool-slurmd
        - name: data
          hostPath:
            path: /nas/slurm/data
            type: Directory
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmd
  labels:
    app: slurmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmd
  template:
    metadata:
      labels:
        app: slurmd
    spec:
      hostname: slurmd
      containers:
      #  slurmd
        - name: slurmd
          image: docker.io/kalenpeterson/slurm-docker-cluster:v18
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/docker-entrypoint.sh"]
          args:
            - "slurmd"
          #command: ["slurmd"]
          # command: ["/bin/sh", "-c"]
          # args:
          #   - "sleep infinity"
          ports:
            - name: slurmd
              protocol: TCP
              containerPort: 6818
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6818
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 5
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6818
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf.injected
              subPath: slurm.conf
              name: slurm-config
            - mountPath: /var/log/slurm
              name: var-log-slurm
            - mountPath: /nas/slurm/data
              name: data
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config
            defaultMode: 0600
        - name: var-log-slurm
          persistentVolumeClaim:
            claimName: var-log-slurm
        # - name: var-lib-slurmd
        #   persistentVolumeClaim:
        #     claimName: var-lib-slurmd
        # - name: var-spool-slurmd
        #   persistentVolumeClaim:
        #     claimName: var-spool-slurmd
        - name: data
          hostPath:
            path: /nas/slurm/data
            type: Directory
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-log-slurm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: panfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-lib-slurmd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: panfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-spool-slurmd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: panfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: slurmdbd-external
  annotations:
    metallb.universe.tf/address-pool: internal-slurmdbd
spec:
  selector:
    app: slurmdbd
  ports:
    - protocol: TCP
      port: 6819
      targetPort: 6819
      name: slurm-slurmdbd
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: slurmctld-external
  annotations:
    metallb.universe.tf/address-pool: internal-slurmctld
spec:
  selector:
    app: slurmctld
  ports:
    - protocol: TCP
      port: 6817
      targetPort: 6817
      name: slurmctld
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: slurmdbd
spec:
  selector:
    app: slurmdbd
  ports:
    - protocol: TCP
      port: 6819
      targetPort: 6819
      name: slurm-slurmdbd
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: slurmctld
spec:
  selector:
    app: slurmctld
  ports:
    - protocol: TCP
      port: 6817
      targetPort: 6817
      name: slurmctld
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: slurmd
spec:
  selector:
    app: slurmd
  ports:
    - protocol: TCP
      port: 6818
      targetPort: 6818
      name: slurmd
  type: ClusterIP
