---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurm-master
  labels:
    app: slurm-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurm-master
  template:
    metadata:
      labels:
        app: slurm-master
    spec:
      containers:
        - name: slurmdbd
          image: slurm-docker-cluster:v1
          imagePullPolicy: IfNotPresent
          command: ["slurmdbd"]
          ports:
            - 6819
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6819
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6819
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf
              name: slurm
            - mountPath: /etc/slurm/slurmdbd.conf
              name: slurmdbd
            - mountPath: /etc/munge
              name: munge
            - mountPath: /var/log/slurm
              name: log
        - name: slurmctld
          image: slurm-docker-cluster:v1
          imagePullPolicy: IfNotPresent
          command: ["slurmctld"]
          ports:
            - 6817
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6817
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 6817
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf
              name: slurm
            - mountPath: /etc/slurm/slurmdbd.conf
              name: slurmdbd
            - mountPath: /etc/munge
              name: munge
            - mountPath: /var/log/slurm
              name: log
            - mountPath: /data
              name: data
        - name: slurmd
          image: slurm-docker-cluster:v1
          imagePullPolicy: IfNotPresent
          command: ["slurmd"]
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf
              name: slurm
            - mountPath: /etc/slurm/slurmdbd.conf
              name: slurmdbd
            - mountPath: /etc/munge
              name: munge
            - mountPath: /var/log/slurm
              name: log
            - mountPath: /data
              name: data
      volumes:
        - name: slurm
          configMap:
            name: slurm-config
            items:
            - key: slurm.conf
              path: keys
        - name: slurmdbd
          configMap:
            name: slurm-config
            items:
            - key: slurmdbd.conf
              path: keys
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: slurm-master
spec:
  selector:
    app: slurm-master
  ports:
    - protocol: TCP
      port: 6817
      targetPort: 6817
    - protocol: TCP
      port: 6818
      targetPort: 6818
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: slurm-config
  namespace: default
data:
  slurm.conf: |
    # slurm.conf
    #
    # See the slurm.conf man page for more information.
    #
    ClusterName=linux
    ControlMachine=slurmctld
    ControlAddr=slurmctld
    #BackupController=
    #BackupAddr=
    #
    SlurmUser=slurm
    #SlurmdUser=root
    SlurmctldPort=6817
    SlurmdPort=6818
    AuthType=auth/munge
    #JobCredentialPrivateKey=
    #JobCredentialPublicCertificate=
    StateSaveLocation=/var/lib/slurmd
    SlurmdSpoolDir=/var/spool/slurmd
    SwitchType=switch/none
    MpiDefault=none
    SlurmctldPidFile=/var/run/slurmd/slurmctld.pid
    SlurmdPidFile=/var/run/slurmd/slurmd.pid
    ProctrackType=proctrack/linuxproc
    #PluginDir=
    CacheGroups=0
    #FirstJobId=
    ReturnToService=0
    #MaxJobCount=
    #PlugStackConfig=
    #PropagatePrioProcess=
    #PropagateResourceLimits=
    #PropagateResourceLimitsExcept=
    #Prolog=
    #Epilog=
    #SrunProlog=
    #SrunEpilog=
    #TaskProlog=
    #TaskEpilog=
    #TaskPlugin=
    #TrackWCKey=no
    #TreeWidth=50
    #TmpFS=
    #UsePAM=
    #
    # TIMERS
    SlurmctldTimeout=300
    SlurmdTimeout=300
    InactiveLimit=0
    MinJobAge=300
    KillWait=30
    Waittime=0
    #
    # SCHEDULING
    SchedulerType=sched/backfill
    #SchedulerAuth=
    #SchedulerPort=
    #SchedulerRootFilter=
    SelectType=select/cons_res
    SelectTypeParameters=CR_CPU_Memory
    FastSchedule=1
    #PriorityType=priority/multifactor
    #PriorityDecayHalfLife=14-0
    #PriorityUsageResetPeriod=14-0
    #PriorityWeightFairshare=100000
    #PriorityWeightAge=1000
    #PriorityWeightPartition=10000
    #PriorityWeightJobSize=1000
    #PriorityMaxAge=1-0
    #
    # LOGGING
    SlurmctldDebug=3
    SlurmctldLogFile=/var/log/slurm/slurmctld.log
    SlurmdDebug=3
    SlurmdLogFile=/var/log/slurm/slurmd.log
    JobCompType=jobcomp/filetxt
    JobCompLoc=/var/log/slurm/jobcomp.log
    #
    # ACCOUNTING
    JobAcctGatherType=jobacct_gather/linux
    JobAcctGatherFrequency=30
    #
    AccountingStorageType=accounting_storage/slurmdbd
    AccountingStorageHost=slurmdbd
    AccountingStoragePort=6819
    AccountingStorageLoc=slurm_acct_db
    #AccountingStoragePass=
    #AccountingStorageUser=
    #
    # COMPUTE NODES
    NodeName=c[1-2] RealMemory=1000 State=UNKNOWN
    #
    # PARTITIONS
    PartitionName=normal Default=yes Nodes=c[1-2] Priority=50 DefMemPerCPU=500 Shared=NO MaxNodes=2 MaxTime=5-00:00:00 DefaultTime=5-00:00:00 State=UP

  slurmdbd.conf: |
    #
    # Example slurmdbd.conf file.
    #
    # See the slurmdbd.conf man page for more information.
    #
    # Archive info
    #ArchiveJobs=yes
    #ArchiveDir="/tmp"
    #ArchiveSteps=yes
    #ArchiveScript=
    #JobPurge=12
    #StepPurge=1
    #
    # Authentication info
    AuthType=auth/munge
    #AuthInfo=/var/run/munge/munge.socket.2
    #
    # slurmDBD info
    DbdAddr=slurmdbd
    DbdHost=slurmdbd
    #DbdPort=6819
    SlurmUser=slurm
    #MessageTimeout=300
    DebugLevel=4
    #DefaultQOS=normal,standby
    LogFile=/var/log/slurm/slurmdbd.log
    PidFile=/var/run/slurmdbd/slurmdbd.pid
    #PluginDir=/usr/lib/slurm
    #PrivateData=accounts,users,usage,jobs
    #TrackWCKey=yes
    #
    # Database info
    StorageType=accounting_storage/mysql
    StorageHost=mysql
    StorageUser=slurm
    StoragePass=password
    StorageLoc=slurm_acct_db