apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  # Config for Lambda Labs Nodes
  config.json: |
    {
        "periodicUpdateInterval": 300,
        "configList": [
           {
             "resourceName": "hca_shared_devices_a",
             "rdmaHcaMax": 50,
             "selectors": {
               "vendors": ["15b3"],
               "deviceIDs": ["101b"],
               "linkTypes": ["infiniband"]
              }
           }
        ]
    }
